--- Config dump file for schema Alarm
DECLARE @TC INT = @@TRANCOUNT;

BEGIN TRY
    BEGIN TRANSACTION;

    -- Begin dump for table Alarm.Behaviour
    UPDATE [Alarm].[Behaviour] SET [Active] = 'False';
    EXEC [Alarm].[DoConfigDefineBehaviour] @Code = 'VOICE', @Name = 'Voice alarms', @Description = 'Voice alarms', @ConfiguratorClassName = null, @ConfiguratorAssemblyName = null, @Active = True;
    -- End dump for table Alarm.Behaviour

    -- Begin dump for table Alarm.Category
    UPDATE [Alarm].[Category] SET [Active] = 'False';
    EXEC [Alarm].[DoConfigDefineCategory] @Code = 'ALM', @Name = 'Alarm', @Description = 'Alarm', @Active = True;
	EXEC [Alarm].[DoConfigDefineCategory] @Code = 'WAR', @Name = 'Warning', @Description = 'Warning', @Active = True;
    -- End dump for table Alarm.Category

    -- Begin dump for table Alarm.Enum
    UPDATE [Alarm].[Enum] SET [Active] = 'False';
    EXEC [Alarm].[DoConfigDefineEnum] @Code = 'HANDSHAKE_ERRORS', @Name = 'Handshake Errors', @Description = 'All possible errors generated while executing handshakes', @Active = True;
    -- End dump for table Alarm.Enum

    -- Begin dump for table Alarm.Group
    UPDATE [Alarm].[Group] SET [Active] = 'False';
    EXEC [Alarm].[DoConfigDefineGroup] @Code = 'MANTENIMIENTO', @Name = 'Mantenimiento', @Description = 'Mantenimiento', @Active = True;
    EXEC [Alarm].[DoConfigDefineGroup] @Code = 'OPERACION', @Name = 'Operación', @Description = 'Operación', @Active = True;
    EXEC [Alarm].[DoConfigDefineGroup] @Code = 'INSTRUMENTACION', @Name = 'Instrumentación', @Description = 'Instrumentación', @Active = True;
   -- End dump for table Alarm.Group

    -- Begin dump for table Alarm.Severity
    UPDATE [Alarm].[Severity] SET [Active] = 'False';
    EXEC [Alarm].[DoConfigDefineSeverity] @Code = 'VERYHIGH', @Name = 'VERYHIGH', @Description = 'Very High Priority', @ColorOn = 10027008, @ColorOff = 10027008, @FontColorOn = 16777215, @FontColorOff = 16777215, @Priority = 1, @Active = True;
    EXEC [Alarm].[DoConfigDefineSeverity] @Code = 'HIGH', @Name = 'HIGH', @Description = 'High Priority', @ColorOn = 16751968, @ColorOff = 16751968, @FontColorOn = 0, @FontColorOff = 0, @Priority = 2, @Active = True;
    EXEC [Alarm].[DoConfigDefineSeverity] @Code = 'LOW', @Name = 'LOW', @Description = 'Low Priority', @ColorOn = 16777152, @ColorOff = 16777152, @FontColorOn = 0, @FontColorOff = 0, @Priority = 3, @Active = True;
	EXEC [Alarm].[DoConfigDefineSeverity] @Code = 'WARNING', @Name = 'WARNING', @Description = 'Warning', @ColorOn = 2012734, @ColorOff = 2012734, @FontColorOn = 0, @FontColorOff = 0, @Priority = 4, @Active = True;
    -- End dump for table Alarm.Severity

    -- Begin dump for table Alarm.Type
    UPDATE [Alarm].[Type] SET [Active] = 'False';
    EXEC [Alarm].[DoConfigDefineType] @Code = 'EMERGENCY', @Name = 'Emergency', @Description = 'EmergencyX', @Active = True;
    EXEC [Alarm].[DoConfigDefineType] @Code = 'FIRST_PIECE', @Name = 'First Piece', @Description = 'First Piece', @Active = True;
    EXEC [Alarm].[DoConfigDefineType] @Code = 'PIECE_PRESENCE', @Name = 'Piece Presence', @Description = 'Piece Presence', @Active = True;
    EXEC [Alarm].[DoConfigDefineType] @Code = 'SEQUENCE', @Name = 'Sequence', @Description = 'Sequence', @Active = True;
    EXEC [Alarm].[DoConfigDefineType] @Code = 'STARTING_CONDITION', @Name = 'Initial Condition', @Description = 'Initial Condition', @Active = True;
    EXEC [Alarm].[DoConfigDefineType] @Code = 'SYSTEM', @Name = 'System', @Description = 'System', @Active = True;
    EXEC [Alarm].[DoConfigDefineType] @Code = 'TRACKING', @Name = 'Tracking', @Description = 'Tracking', @Active = True;
    -- End dump for table Alarm.Type

    -- Begin dump for table Alarm.EnumValue
    UPDATE [Alarm].[EnumValue] SET [Active] = 'False';
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChangeProduct:-1', @Name = 'ProdChangeProduct:GeneralErrorRecoverable', @Description = ' Production: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChangeProduct:-101', @Name = 'ProdChangeProduct:GeneralErrorNoRecoverable', @Description = ' Production: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChangeProduct:-102', @Name = 'ProdChangeProduct:IdTrkNotFound', @Description = ' Production: Tracking ID Not Found in DB', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChangeProduct:-103', @Name = 'ProdChangeProduct:IdTrkPassNotInMachine', @Description = ' Production: TrackingPass ID Does Not Belong to Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChangeProduct:-104', @Name = 'ProdChangeProduct:IdBatchNotFound', @Description = ' Production: Received Invalid Batch ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChangeProduct:-105', @Name = 'ProdChangeProduct:NonValidItemStatus', @Description = ' Production: Received Invalid Item Status', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChangeProduct:-106', @Name = 'ProdChangeProduct:NonValidItemCount', @Description = ' Production: Received Invalid Item Count', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChangeProduct:-107', @Name = 'ProdChangeProduct:NonValidWorkTime', @Description = ' Production: Received Invalid WorkTime', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChangeProduct:-109', @Name = 'ProdChangeProduct:NonValidValChgProduct', @Description = ' Production: Received Invalid ValidateProduct/ChangeProduct', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChangeProduct:-110', @Name = 'ProdChangeProduct:NonValidIdTracking', @Description = ' Production: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChangeProduct:-112', @Name = 'ProdChangeProduct:CannotAutoChgBatch', @Description = ' Production: Cannot Change Active Product in Machine Automatically', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChangeProduct:-2', @Name = 'ProdChangeProduct:NoActiveBatchFound', @Description = ' Production: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChangeProduct:-3', @Name = 'ProdChangeProduct:IdTrkFromDifferentBatch', @Description = ' Production: Received Tracking ID Does Not Belong to Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCheckProduct:-1', @Name = 'ProdCheckProduct:GeneralErrorRecoverable', @Description = ' Production: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCheckProduct:-101', @Name = 'ProdCheckProduct:GeneralErrorNoRecoverable', @Description = ' Production: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCheckProduct:-102', @Name = 'ProdCheckProduct:IdTrkNotFound', @Description = ' Production: Tracking ID Not Found in DB', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCheckProduct:-103', @Name = 'ProdCheckProduct:IdTrkPassNotInMachine', @Description = ' Production: TrackingPass ID Does Not Belong to Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCheckProduct:-104', @Name = 'ProdCheckProduct:IdBatchNotFound', @Description = ' Production: Received Invalid Batch ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCheckProduct:-105', @Name = 'ProdCheckProduct:NonValidItemStatus', @Description = ' Production: Received Invalid Item Status', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCheckProduct:-106', @Name = 'ProdCheckProduct:NonValidItemCount', @Description = ' Production: Received Invalid Item Count', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCheckProduct:-107', @Name = 'ProdCheckProduct:NonValidWorkTime', @Description = ' Production: Received Invalid WorkTime', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCheckProduct:-109', @Name = 'ProdCheckProduct:NonValidValChgProduct', @Description = ' Production: Received Invalid ValidateProduct/ChangeProduct', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCheckProduct:-110', @Name = 'ProdCheckProduct:NonValidIdTracking', @Description = ' Production: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCheckProduct:-112', @Name = 'ProdCheckProduct:CannotAutoChgBatch', @Description = ' Production: Cannot Change Active Product in Machine Automatically', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCheckProduct:-2', @Name = 'ProdCheckProduct:NoActiveBatchFound', @Description = ' Production: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCheckProduct:-3', @Name = 'ProdCheckProduct:IdTrkFromDifferentBatch', @Description = ' Production: Received Tracking ID Does Not Belong to Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoad:-1', @Name = 'ProdChPrLoad:GeneralErrorRecoverable', @Description = ' Production: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoad:-101', @Name = 'ProdChPrLoad:GeneralErrorNoRecoverable', @Description = ' Production: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoad:-102', @Name = 'ProdChPrLoad:IdTrkNotFound', @Description = ' Production: Tracking ID Not Found in DB', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoad:-103', @Name = 'ProdChPrLoad:IdTrkPassNotInMachine', @Description = ' Production: TrackingPass ID Does Not Belong to Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoad:-104', @Name = 'ProdChPrLoad:IdBatchNotFound', @Description = ' Production: Received Invalid Batch ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoad:-105', @Name = 'ProdChPrLoad:NonValidItemStatus', @Description = ' Production: Received Invalid Item Status', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoad:-106', @Name = 'ProdChPrLoad:NonValidItemCount', @Description = ' Production: Received Invalid Item Count', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoad:-107', @Name = 'ProdChPrLoad:NonValidWorkTime', @Description = ' Production: Received Invalid WorkTime', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoad:-109', @Name = 'ProdChPrLoad:NonValidValChgProduct', @Description = ' Production: Received Invalid ValidateProduct/ChangeProduct', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoad:-110', @Name = 'ProdChPrLoad:NonValidIdTracking', @Description = ' Production: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoad:-112', @Name = 'ProdChPrLoad:CannotAutoChgBatch', @Description = ' Production: Cannot Change Active Product in Machine Automatically', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoad:-2', @Name = 'ProdChPrLoad:NoActiveBatchFound', @Description = ' Production: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoad:-3', @Name = 'ProdChPrLoad:IdTrkFromDifferentBatch', @Description = ' Production: Received Tracking ID Does Not Belong to Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoadCount:-1', @Name = 'ProdChPrLoadCount:GeneralErrorRecoverable', @Description = ' Production: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoadCount:-101', @Name = 'ProdChPrLoadCount:GeneralErrorNoRecoverable', @Description = ' Production: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoadCount:-102', @Name = 'ProdChPrLoadCount:IdTrkNotFound', @Description = ' Production: Tracking ID Not Found in DB', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoadCount:-103', @Name = 'ProdChPrLoadCount:IdTrkPassNotInMachine', @Description = ' Production: TrackingPass ID Does Not Belong to Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoadCount:-104', @Name = 'ProdChPrLoadCount:IdBatchNotFound', @Description = ' Production: Received Invalid Batch ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoadCount:-105', @Name = 'ProdChPrLoadCount:NonValidItemStatus', @Description = ' Production: Received Invalid Item Status', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoadCount:-106', @Name = 'ProdChPrLoadCount:NonValidItemCount', @Description = ' Production: Received Invalid Item Count', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoadCount:-107', @Name = 'ProdChPrLoadCount:NonValidWorkTime', @Description = ' Production: Received Invalid WorkTime', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoadCount:-109', @Name = 'ProdChPrLoadCount:NonValidValChgProduct', @Description = ' Production: Received Invalid ValidateProduct/ChangeProduct', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoadCount:-110', @Name = 'ProdChPrLoadCount:NonValidIdTracking', @Description = ' Production: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoadCount:-112', @Name = 'ProdChPrLoadCount:CannotAutoChgBatch', @Description = ' Production: Cannot Change Active Product in Machine Automatically', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoadCount:-2', @Name = 'ProdChPrLoadCount:NoActiveBatchFound', @Description = ' Production: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdChPrLoadCount:-3', @Name = 'ProdChPrLoadCount:IdTrkFromDifferentBatch', @Description = ' Production: Received Tracking ID Does Not Belong to Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCount:-1', @Name = 'ProdCount:GeneralErrorRecoverable', @Description = ' Production: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCount:-101', @Name = 'ProdCount:GeneralErrorNoRecoverable', @Description = ' Production: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCount:-102', @Name = 'ProdCount:IdTrkNotFound', @Description = ' Production: Tracking ID Not Found in DB', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCount:-103', @Name = 'ProdCount:IdTrkPassNotInMachine', @Description = ' Production: TrackingPass ID Does Not Belong to Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCount:-104', @Name = 'ProdCount:IdBatchNotFound', @Description = ' Production: Received Invalid Batch ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCount:-105', @Name = 'ProdCount:NonValidItemStatus', @Description = ' Production: Received Invalid Item Status', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCount:-106', @Name = 'ProdCount:NonValidItemCount', @Description = ' Production: Received Invalid Item Count', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCount:-107', @Name = 'ProdCount:NonValidWorkTime', @Description = ' Production: Received Invalid WorkTime', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCount:-109', @Name = 'ProdCount:NonValidValChgProduct', @Description = ' Production: Received Invalid ValidateProduct/ChangeProduct', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCount:-110', @Name = 'ProdCount:NonValidIdTracking', @Description = ' Production: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCount:-112', @Name = 'ProdCount:CannotAutoChgBatch', @Description = ' Production: Cannot Change Active Product in Machine Automatically', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCount:-2', @Name = 'ProdCount:NoActiveBatchFound', @Description = ' Production: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdCount:-3', @Name = 'ProdCount:IdTrkFromDifferentBatch', @Description = ' Production: Received Tracking ID Does Not Belong to Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoad:-1', @Name = 'ProdLoad:GeneralErrorRecoverable', @Description = ' Production: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoad:-101', @Name = 'ProdLoad:GeneralErrorNoRecoverable', @Description = ' Production: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoad:-102', @Name = 'ProdLoad:IdTrkNotFound', @Description = ' Production: Tracking ID Not Found in DB', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoad:-103', @Name = 'ProdLoad:IdTrkPassNotInMachine', @Description = ' Production: TrackingPass ID Does Not Belong to Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoad:-104', @Name = 'ProdLoad:IdBatchNotFound', @Description = ' Production: Received Invalid Batch ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoad:-105', @Name = 'ProdLoad:NonValidItemStatus', @Description = ' Production: Received Invalid Item Status', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoad:-106', @Name = 'ProdLoad:NonValidItemCount', @Description = ' Production: Received Invalid Item Count', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoad:-107', @Name = 'ProdLoad:NonValidWorkTime', @Description = ' Production: Received Invalid WorkTime', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoad:-109', @Name = 'ProdLoad:NonValidValChgProduct', @Description = ' Production: Received Invalid ValidateProduct/ChangeProduct', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoad:-110', @Name = 'ProdLoad:NonValidIdTracking', @Description = ' Production: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoad:-112', @Name = 'ProdLoad:CannotAutoChgBatch', @Description = ' Production: Cannot Change Active Product in Machine Automatically', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoad:-2', @Name = 'ProdLoad:NoActiveBatchFound', @Description = ' Production: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoad:-3', @Name = 'ProdLoad:IdTrkFromDifferentBatch', @Description = ' Production: Received Tracking ID Does Not Belong to Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoadCount:-1', @Name = 'ProdLoadCount:GeneralErrorRecoverable', @Description = ' Production: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoadCount:-101', @Name = 'ProdLoadCount:GeneralErrorNoRecoverable', @Description = ' Production: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoadCount:-102', @Name = 'ProdLoadCount:IdTrkNotFound', @Description = ' Production: Tracking ID Not Found in DB', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoadCount:-103', @Name = 'ProdLoadCount:IdTrkPassNotInMachine', @Description = ' Production: TrackingPass ID Does Not Belong to Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoadCount:-104', @Name = 'ProdLoadCount:IdBatchNotFound', @Description = ' Production: Received Invalid Batch ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoadCount:-105', @Name = 'ProdLoadCount:NonValidItemStatus', @Description = ' Production: Received Invalid Item Status', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoadCount:-106', @Name = 'ProdLoadCount:NonValidItemCount', @Description = ' Production: Received Invalid Item Count', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoadCount:-107', @Name = 'ProdLoadCount:NonValidWorkTime', @Description = ' Production: Received Invalid WorkTime', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoadCount:-109', @Name = 'ProdLoadCount:NonValidValChgProduct', @Description = ' Production: Received Invalid ValidateProduct/ChangeProduct', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoadCount:-110', @Name = 'ProdLoadCount:NonValidIdTracking', @Description = ' Production: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoadCount:-112', @Name = 'ProdLoadCount:CannotAutoChgBatch', @Description = ' Production: Cannot Change Active Product in Machine Automatically', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoadCount:-2', @Name = 'ProdLoadCount:NoActiveBatchFound', @Description = ' Production: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'ProdLoadCount:-3', @Name = 'ProdLoadCount:IdTrkFromDifferentBatch', @Description = ' Production: Received Tracking ID Does Not Belong to Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TdaPHanshake1:-1', @Name = 'TdaPHanshake1:GeneralErrorRecoverable', @Description = ' TDA: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TdaPHanshake1:-101', @Name = 'TdaPHanshake1:GeneralErrorNoRecoverable', @Description = ' TDA: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TdaPHanshake1:-102', @Name = 'TdaPHanshake1:InvalidIdTracking', @Description = ' TDA: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TdaPHanshake1:-103', @Name = 'TdaPHanshake1:InvalidIdTrackingPass', @Description = ' TDA: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TdaPHanshake1:-104', @Name = 'TdaPHanshake1:InvalidIdKeyHistory', @Description = ' TDA: Received Invalid Key ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TdaPHanshake1:-3', @Name = 'TdaPHanshake1:DatabaseError', @Description = ' TDA: Database Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCheck:-1', @Name = 'TrkCheck:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCheck:-101', @Name = 'TrkCheck:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCheck:-102', @Name = 'TrkCheck:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCheck:-105', @Name = 'TrkCheck:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCheck:-2', @Name = 'TrkCheck:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCheck:-3', @Name = 'TrkCheck:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCheck:-6', @Name = 'TrkCheck:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCloneAll:-1', @Name = 'TrkCloneAll:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCloneAll:-101', @Name = 'TrkCloneAll:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCloneAll:-102', @Name = 'TrkCloneAll:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCloneAll:-105', @Name = 'TrkCloneAll:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCloneAll:-2', @Name = 'TrkCloneAll:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCloneAll:-3', @Name = 'TrkCloneAll:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCloneAll:-6', @Name = 'TrkCloneAll:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCreate:-1', @Name = 'TrkCreate:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCreate:-101', @Name = 'TrkCreate:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCreate:-102', @Name = 'TrkCreate:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCreate:-105', @Name = 'TrkCreate:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCreate:-2', @Name = 'TrkCreate:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCreate:-3', @Name = 'TrkCreate:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkCreate:-6', @Name = 'TrkCreate:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdata:-1', @Name = 'TrkGetdata:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdata:-101', @Name = 'TrkGetdata:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdata:-102', @Name = 'TrkGetdata:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdata:-105', @Name = 'TrkGetdata:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdata:-2', @Name = 'TrkGetdata:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdata:-3', @Name = 'TrkGetdata:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdata:-6', @Name = 'TrkGetdata:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdataExt:-1', @Name = 'TrkGetdataExt:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdataExt:-101', @Name = 'TrkGetdataExt:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdataExt:-102', @Name = 'TrkGetdataExt:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdataExt:-105', @Name = 'TrkGetdataExt:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdataExt:-2', @Name = 'TrkGetdataExt:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdataExt:-3', @Name = 'TrkGetdataExt:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdataExt:-6', @Name = 'TrkGetdataExt:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdataExt2:-1', @Name = 'TrkGetdataExt2:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdataExt2:-101', @Name = 'TrkGetdataExt2:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdataExt2:-102', @Name = 'TrkGetdataExt2:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdataExt2:-105', @Name = 'TrkGetdataExt2:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdataExt2:-2', @Name = 'TrkGetdataExt2:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdataExt2:-3', @Name = 'TrkGetdataExt2:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkGetdataExt2:-6', @Name = 'TrkGetdataExt2:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkMaskedShift:-1', @Name = 'TrkMaskedShift:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkMaskedShift:-101', @Name = 'TrkMaskedShift:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkMaskedShift:-102', @Name = 'TrkMaskedShift:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkMaskedShift:-105', @Name = 'TrkMaskedShift:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkMaskedShift:-2', @Name = 'TrkMaskedShift:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkMaskedShift:-3', @Name = 'TrkMaskedShift:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkMaskedShift:-6', @Name = 'TrkMaskedShift:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkMaskedShiftFull:-1', @Name = 'TrkMaskedShiftFull:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkMaskedShiftFull:-101', @Name = 'TrkMaskedShiftFull:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkMaskedShiftFull:-102', @Name = 'TrkMaskedShiftFull:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkMaskedShiftFull:-105', @Name = 'TrkMaskedShiftFull:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkMaskedShiftFull:-2', @Name = 'TrkMaskedShiftFull:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkMaskedShiftFull:-3', @Name = 'TrkMaskedShiftFull:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkMaskedShiftFull:-6', @Name = 'TrkMaskedShiftFull:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShift:-1', @Name = 'TrkShift:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShift:-101', @Name = 'TrkShift:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShift:-102', @Name = 'TrkShift:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShift:-105', @Name = 'TrkShift:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShift:-2', @Name = 'TrkShift:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShift:-3', @Name = 'TrkShift:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShift:-6', @Name = 'TrkShift:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftAlsoFull:-1', @Name = 'TrkShiftAlsoFull:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftAlsoFull:-101', @Name = 'TrkShiftAlsoFull:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftAlsoFull:-102', @Name = 'TrkShiftAlsoFull:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftAlsoFull:-105', @Name = 'TrkShiftAlsoFull:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftAlsoFull:-2', @Name = 'TrkShiftAlsoFull:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftAlsoFull:-3', @Name = 'TrkShiftAlsoFull:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftAlsoFull:-6', @Name = 'TrkShiftAlsoFull:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftAlsoFullTrs:-1', @Name = 'TrkShiftAlsoFullTrs:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftAlsoFullTrs:-101', @Name = 'TrkShiftAlsoFullTrs:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftAlsoFullTrs:-102', @Name = 'TrkShiftAlsoFullTrs:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftAlsoFullTrs:-105', @Name = 'TrkShiftAlsoFullTrs:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftAlsoFullTrs:-2', @Name = 'TrkShiftAlsoFullTrs:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftAlsoFullTrs:-3', @Name = 'TrkShiftAlsoFullTrs:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftAlsoFullTrs:-6', @Name = 'TrkShiftAlsoFullTrs:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTemplate:-1', @Name = 'TrkShiftTemplate:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTemplate:-101', @Name = 'TrkShiftTemplate:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTemplate:-102', @Name = 'TrkShiftTemplate:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTemplate:-105', @Name = 'TrkShiftTemplate:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTemplate:-2', @Name = 'TrkShiftTemplate:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTemplate:-3', @Name = 'TrkShiftTemplate:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTemplate:-6', @Name = 'TrkShiftTemplate:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTemplFull:-1', @Name = 'TrkShiftTemplFull:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTemplFull:-101', @Name = 'TrkShiftTemplFull:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTemplFull:-102', @Name = 'TrkShiftTemplFull:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTemplFull:-105', @Name = 'TrkShiftTemplFull:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTemplFull:-2', @Name = 'TrkShiftTemplFull:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTemplFull:-3', @Name = 'TrkShiftTemplFull:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTemplFull:-6', @Name = 'TrkShiftTemplFull:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTransfer:-1', @Name = 'TrkShiftTransfer:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTransfer:-101', @Name = 'TrkShiftTransfer:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTransfer:-102', @Name = 'TrkShiftTransfer:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTransfer:-105', @Name = 'TrkShiftTransfer:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTransfer:-2', @Name = 'TrkShiftTransfer:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTransfer:-3', @Name = 'TrkShiftTransfer:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkShiftTransfer:-6', @Name = 'TrkShiftTransfer:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransfer:-1', @Name = 'TrkTransfer:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransfer:-101', @Name = 'TrkTransfer:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransfer:-102', @Name = 'TrkTransfer:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransfer:-105', @Name = 'TrkTransfer:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransfer:-2', @Name = 'TrkTransfer:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransfer:-3', @Name = 'TrkTransfer:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransfer:-6', @Name = 'TrkTransfer:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferIfAvail:-1', @Name = 'TrkTransferIfAvail:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferIfAvail:-101', @Name = 'TrkTransferIfAvail:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferIfAvail:-102', @Name = 'TrkTransferIfAvail:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferIfAvail:-105', @Name = 'TrkTransferIfAvail:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferIfAvail:-2', @Name = 'TrkTransferIfAvail:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferIfAvail:-3', @Name = 'TrkTransferIfAvail:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferIfAvail:-6', @Name = 'TrkTransferIfAvail:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferShift:-1', @Name = 'TrkTransferShift:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferShift:-101', @Name = 'TrkTransferShift:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferShift:-102', @Name = 'TrkTransferShift:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferShift:-105', @Name = 'TrkTransferShift:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferShift:-2', @Name = 'TrkTransferShift:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferShift:-3', @Name = 'TrkTransferShift:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferShift:-6', @Name = 'TrkTransferShift:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferTransfer:-1', @Name = 'TrkTransferTransfer:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferTransfer:-101', @Name = 'TrkTransferTransfer:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferTransfer:-102', @Name = 'TrkTransferTransfer:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferTransfer:-105', @Name = 'TrkTransferTransfer:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferTransfer:-2', @Name = 'TrkTransferTransfer:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferTransfer:-3', @Name = 'TrkTransferTransfer:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransferTransfer:-6', @Name = 'TrkTransferTransfer:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransFirstAvail:-1', @Name = 'TrkTransFirstAvail:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransFirstAvail:-101', @Name = 'TrkTransFirstAvail:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransFirstAvail:-102', @Name = 'TrkTransFirstAvail:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransFirstAvail:-105', @Name = 'TrkTransFirstAvail:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransFirstAvail:-2', @Name = 'TrkTransFirstAvail:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransFirstAvail:-3', @Name = 'TrkTransFirstAvail:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransFirstAvail:-6', @Name = 'TrkTransFirstAvail:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransFirstAvShift:-1', @Name = 'TrkTransFirstAvShift:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransFirstAvShift:-101', @Name = 'TrkTransFirstAvShift:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransFirstAvShift:-102', @Name = 'TrkTransFirstAvShift:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransFirstAvShift:-105', @Name = 'TrkTransFirstAvShift:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransFirstAvShift:-2', @Name = 'TrkTransFirstAvShift:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransFirstAvShift:-3', @Name = 'TrkTransFirstAvShift:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransFirstAvShift:-6', @Name = 'TrkTransFirstAvShift:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransMaskedShift:-1', @Name = 'TrkTransMaskedShift:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransMaskedShift:-101', @Name = 'TrkTransMaskedShift:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransMaskedShift:-102', @Name = 'TrkTransMaskedShift:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransMaskedShift:-105', @Name = 'TrkTransMaskedShift:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransMaskedShift:-2', @Name = 'TrkTransMaskedShift:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransMaskedShift:-3', @Name = 'TrkTransMaskedShift:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransMaskedShift:-6', @Name = 'TrkTransMaskedShift:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransShiftTrans:-1', @Name = 'TrkTransShiftTrans:GeneralErrorRecoverable', @Description = ' Tracking: Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransShiftTrans:-101', @Name = 'TrkTransShiftTrans:GeneralErrorNoRecoverable', @Description = ' Tracking: Non Recoverable Error', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransShiftTrans:-102', @Name = 'TrkTransShiftTrans:InvalidIdTracking', @Description = ' Tracking: Received Invalid Tracking ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransShiftTrans:-105', @Name = 'TrkTransShiftTrans:InvalidIdTrackingPass', @Description = ' Tracking: Received Invalid TrackingPass ID', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransShiftTrans:-2', @Name = 'TrkTransShiftTrans:DestinationZoneFull', @Description = ' Tracking: Destination Zone is Full', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransShiftTrans:-3', @Name = 'TrkTransShiftTrans:SourceZoneEmpty', @Description = ' Tracking: Source Zone is Empty', @SuggestionUri = null, @Active = True;
    EXEC [Alarm].[DoConfigDefineEnumValue] @EnumCode = 'HANDSHAKE_ERRORS', @SeverityCode = 'HIGH', @PlcCode = 1, @Code = 'TrkTransShiftTrans:-6', @Name = 'TrkTransShiftTrans:NoActiveProductionFound', @Description = ' Tracking: There is No Active Product in Machine', @SuggestionUri = null, @Active = True;
    -- End dump for table Alarm.EnumValue

    -- Begin dump for table Alarm.Tag
    -- End dump for table Alarm.Tag

    -- Begin dump for table Alarm.Alarm
    -- End dump for table Alarm.Alarm

    -- Begin dump for table Alarm.AlarmBehaviour
    -- End dump for table Alarm.AlarmBehaviour

    -- Begin dump for table Alarm.AlarmGroup
    -- End dump for table Alarm.AlarmGroup

    COMMIT TRANSACTION;
END TRY

BEGIN CATCH

    SELECT
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_SEVERITY() AS ErrorSeverity,
        ERROR_STATE() AS ErrorState ,
        ERROR_PROCEDURE() AS ErrorProcedure,
        ERROR_LINE() AS ErrorLine,
        ERROR_MESSAGE() AS ErrorMessage;

    IF @TC > 0 AND XACT_STATE() = 1
        COMMIT TRANSACTION;
    IF @TC = 0
        ROLLBACK TRANSACTION;
END CATCH;
