CREATE TABLE [Custom].[TrackingSpecificationAttribute] (
    [idTrackingSpecificationAttribute] INT                  IDENTITY (1, 1) NOT NULL,
    [idTrackingAttribute]              INT                  NOT NULL,
    [idSpecificationComponentSubType]  INT                  NOT NULL,
    [idSpecificationAttribute]         INT                  NOT NULL,
    [idArea]                           INT                  NULL,
    [idMachineWorkflow]                INT                  NULL,
    [idMachine]                        INT                  NULL,
    [idMachineWorkflowSequence]        INT                  NULL,
    [Active]                           [Common].[TActive]   CONSTRAINT [DF_TrackingSpecificationAttribute_Active] DEFAULT ((1)) NOT NULL,
    [InsDateTime]                      [Common].[TDateTime] CONSTRAINT [DF_TrackingSpecificationAttribute_InsDateTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [UpdDateTime]                      [Common].[TDateTime] CONSTRAINT [DF_TrackingSpecificationAttribute_UpdDateTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    CONSTRAINT [PK_TrackingSpecificationAttribute] PRIMARY KEY CLUSTERED ([idTrackingSpecificationAttribute] ASC),
    CONSTRAINT [UK_Custom_TrackingSpecificationAttribute_idTrackingAttribute_idSpecificationComponentSubType_idSpecificationAttribute] UNIQUE NONCLUSTERED ([idTrackingAttribute] ASC, [idSpecificationComponentSubType] ASC, [idSpecificationAttribute] ASC)
);


GO
--------------------------------------------------------------------------------
-- <auto-generated>
--     This trigger was generated by the DBA.
--     Changes to this script may cause incorrect behavior and will be lost if
--     the trigger is regenerated.
-- </auto-generated>
--------------------------------------------------------------------------------
CREATE TRIGGER [Custom].[OnUpdateTrackingSpecificationAttribute]
ON [Custom].[TrackingSpecificationAttribute]
AFTER UPDATE
NOT FOR REPLICATION
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @Now Common.TDateTime = SYSDATETIMEOFFSET()
	UPDATE [Custom].[TrackingSpecificationAttribute] SET UpdDateTime = @Now
	FROM Inserted I
	INNER JOIN [Custom].[TrackingSpecificationAttribute] T ON   T.idTrackingSpecificationAttribute = I.idTrackingSpecificationAttribute
END