CREATE TABLE [Custom].[Machine] (
    [idMachine]           INT                  NOT NULL,
    [ProductionSortOrder] INT                  NOT NULL,
    [InsDateTime]         [Common].[TDateTime] CONSTRAINT [DF_Machine_InsDateTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [UpdDateTime]         [Common].[TDateTime] CONSTRAINT [DF_Machine_UpdDateTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
    CONSTRAINT [PK_Machine] PRIMARY KEY CLUSTERED ([idMachine] ASC),
    CONSTRAINT [FK_Machine_Machine] FOREIGN KEY ([idMachine]) REFERENCES [Production].[Machine] ([idMachine]),
    CONSTRAINT [UK_Custom_Machine_idMachine] UNIQUE NONCLUSTERED ([idMachine] ASC)
);


GO
--------------------------------------------------------------------------------
-- <auto-generated>
--     This trigger was generated by the DBA.
--     Changes to this script may cause incorrect behavior and will be lost if
--     the trigger is regenerated.
-- </auto-generated>
--------------------------------------------------------------------------------
CREATE TRIGGER [Custom].[OnUpdateMachine]
ON Custom.Machine
AFTER UPDATE
NOT FOR REPLICATION
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @Now Common.TDateTime = SYSDATETIMEOFFSET()
	UPDATE [Custom].[Machine] SET UpdDateTime = @Now
	FROM Inserted I
	INNER JOIN [Custom].[Machine] T ON   T.idMachine = I.idMachine
END