CREATE TABLE [Custom].[TrackingHslColor](
	[idTrackingHslColor] [int] IDENTITY(1,1) NOT NULL,
	[H] [int] NOT NULL,
	[S] [int] NOT NULL,
	[L] [int] NOT NULL,
	[SortOrder] [int] NOT NULL,
	[Active] [Common].[TActive] NOT NULL,
	[InsDateTime] [Common].[TDateTime] CONSTRAINT [DF_TrackingHslColor_InsDateTime] DEFAULT (sysdatetimeoffset())NOT NULL,
	[UpdDateTime] [Common].[TDateTime] CONSTRAINT [DF_TrackingHslColor_UpdDateTime] DEFAULT (sysdatetimeoffset()) NOT NULL,
	CONSTRAINT [PK_TrackingHslColor] PRIMARY KEY CLUSTERED 
(
	[idTrackingHslColor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_Custom_TrackingHslColor_H,S,L,SortOrder] UNIQUE NONCLUSTERED 
(
	[H] ASC,
	[S] ASC,
	[L] ASC,
	[SortOrder] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

--------------------------------------------------------------------------------
-- <auto-generated>
--     This trigger was generated by the DBA.
--     Changes to this script may cause incorrect behavior and will be lost if
--     the trigger is regenerated.
-- </auto-generated>
--------------------------------------------------------------------------------
CREATE TRIGGER [Custom].[OnUpdateTrackingHslColor]
ON [Custom].[TrackingHslColor]
AFTER UPDATE
NOT FOR REPLICATION
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @Now Common.TDateTime = SYSDATETIMEOFFSET()
	UPDATE [Custom].[TrackingHslColor] SET UpdDateTime = @Now
	FROM Inserted I
	INNER JOIN [Custom].[TrackingHslColor] T ON   T.idTrackingHslColor = I.idTrackingHslColor
END