
--------------------------------------------------------------------------------
-- <auto-generated>
--     This view was generated by the DBA.
--     Changes to this script may cause incorrect behavior and will be lost if
--     the view is regenerated.
-- </auto-generated>
--------------------------------------------------------------------------------
CREATE VIEW [Custom].[VwQualityRequiredApplication]
AS
		SELECT *
		FROM [Custom].[QualityRequiredApplication]
		WHERE Active = 1