--------------------------------------------------------------------------------
-- <auto-generated>
--     This view was generated by the DBA.
--     Changes to this script may cause incorrect behavior and will be lost if
--     the view is regenerated.
-- </auto-generated>
--------------------------------------------------------------------------------
CREATE VIEW [Custom].[VwTrackingHslColor]
AS
		SELECT *
		FROM [Custom].[TrackingHslColor]
		WHERE Active = 1